### ISSUE TITLE
rm: cannot remove '/tmp/webtorrent/': Is a directory

### ISSUE THREAD

**Issue by smhmd** [noctuid/mpv-webtorrent-hook#1]
Are you missing a `-rf` flag?
https://github.com/noctuid/mpv-webtorrent-hook/blob/afb5a500ec9f71a7b95dd7c7c596e09d587c32b1/webtorrent-hook.lua#L94
```
rm: cannot remove '/tmp/webtorrent/Death Of A Salesman (1985) [BluRay] [1080p] [YTS.LT]': Is a directory
```

**Comment by noctuid** [comment]
Yeah, for now not all torrents will work great, but I've updated it to delete directories. I opened in issue on webtorrent to have it output things in a format that will allow handling multiple files and always using the file name as the title instead of the directory name when there's a directory.
