### ISSUE TITLE
Handling of multiple magnets as mpv arguments

### ISSUE THREAD

**Issue by dtop129** [noctuid/mpv-webtorrent-hook#10]
If i try opening multiple magnets, the script just opens the first, ignoring the others.

For example

`mpv magnet1 magnet2 ...`

results in mpv only opening **magnet1**

I also tried opening magnets together with normal files(`mpv magnet1 videofile1`), and the same things happen, only magnet1 is opened, but in this case, webtorrent_hook gives some errors

`[webtorrent_hook] tail: write error: Broken pipe`
`[webtorrent_hook] tail: write error`

Both cases work as expected using mpv-btfs-stream

**Comment by noctuid** [comment]
Thanks for reporting, try now.
