### ISSUE TITLE
Title Log

### ISSUE THREAD

**Issue by smhmd** [noctuid/mpv-webtorrent-hook#2]
What do you think about doing away with logs such as:
```
[webtorrent] Setting media title to: Death Of A Salesman (1985) [BluRay] [1080p] [YTS.LT]
```

and the title in these:
```
[webtorrent] Closing webtorrent for Death Of A Salesman (1985) [BluRay] [1080p] [YTS.LT]
[webtorrent] Removing media file for Death Of A Salesman (1985) [BluRay] [1080p] [YTS.LT]
```
They pollute the output a little bit. I don't wish to remove logs entirely. `starting`, `waiting`, and so on are very useful.

**Comment by noctuid** [comment]
Updated it to only output the waiting and up messages by default.
