### ISSUE TITLE
Unable to view torrent - http Internet Error -4

### ISSUE THREAD

**Issue by nohaboat** [noctuid/mpv-webtorrent-hook#23]
![Screenshot_2024-11-29-18-50-17_](https://github.com/user-attachments/assets/4cb6905e-58fa-478e-a7e3-29c0504e2158)
I don't know what is the error. it seems xidel is unable to parse or access html page. Please let me know if you can figure out what the solution is.

[webtorrent_hook] Waiting for webtorrent server
[webtorrent_hook] Error:
[webtorrent_hook] Internet Error: -4 
[webtorrent_hook] when talking to: http://localhost:8000/
[webtorrent_hook] Webtorrent server is up
Speed: 229 B/s Downloaded: 0 B/3.7 GB Uploaded: 302 B [webtorrent_hook] Waiting for webtorrent server
tail: /tmp/webtorrent-hook/6438f083763d38fa991aeb77ad544e82f49241ed/webtorrent-output: file truncated
Speed: 9.6 KB/s Downloaded: 16 KB/3.7 GB Uploaded: 651 B [webtorrent_hook] Error:
[webtorrent_hook] Internet Error: -4 
[webtorrent_hook] when talking to: http://localhost:8000/
[webtorrent_hook] Webtorrent server is up
Failed to recognize file format.
[SimpleHistory] Failed to add into history
Speed: 9.6 KB/s Downloaded: 16 KB/3.7 GB Uploaded: 651 B Exiting... (Errors when loading file)
rm: cannot remove '/tmp/webtorrent-hook/6438f083763d38fa991aeb77ad544e82f49241ed': No such file or directory

**Comment by noctuid** [comment]
Try the latest versoin
