### ISSUE TITLE
webtorrent-wrap.sh failed to capture torrent info for more than one running instance

### ISSUE THREAD

**Issue by toomyzoom** [noctuid/mpv-webtorrent-hook#24]
This seem like behavior change in 5.1.3 (2.5.10) version. The default http server port used to be 8000 for the 1st instance and the subsequent instances will pick random port if that port is occupied. It's no longer behave that way. The next instance after the 1st will hang, insisting to wait for port 8000 to be released. This causes webtorrent-wrap.sh to never return the streaming link back to main.lua/start_webtorrent(). I have to add `-p 0` to webtorrent call for the script so the os will pick random port for it to work.

Original:
`nohup webtorrent download "$@" --out "$out_dir" --keep-seeding \`
Modified:
`nohup webtorrent download "$@" -p 0 --out "$out_dir" --keep-seeding \`

**Comment by noctuid** [comment]
The readme already recommends not setting port in webtorrent_flags. I think it's fine to just always use `--port 0` for now.  If someone wants to be able to control the port, I can make it the default in webtorrent_flags instead, so it can be changed.
