### ISSUE TITLE
Tip: BTFS, webtorrent alternative

### ISSUE THREAD

**Issue by smhmd** [noctuid/mpv-webtorrent-hook#5]
Just letting you know about this great tool for interacting with torrent files.
https://github.com/johang/btfs

**Comment by noctuid** [comment]
Thanks. See [mpv-btfs-hook](https://github.com/noctuid/mpv-btfs-hook). It is much easier to use (can support torrents containing multiple videos or images) but is unfortunately slower than webtorrent.
