### ISSUE TITLE
Escape apostrophes in file names

### ISSUE THREAD

**Issue by TheHardew** [noctuid/mpv-webtorrent-hook#6]
If a file contain's an apostrophe it won't be deleted. On linux, file names can contain any character other than null and forward slash.

From https://unix.stackexchange.com/a/357932 I think the solution would be to run `path = string.gsub(path, "'", "'\\''")` before `os.execute("rm -r '" .. path .. "'")`. This properly deletes the file, but I'm not sure if it doesn't have some other unwanted quirks/bugs.

**Comment by TheHardew** [comment]
Oh also I guess you should change `os.execute("rm -r '" .. path .. "'")` to `os.execute("rm -r -- '" .. path .. "'")` so that `rm` doesn't capture a part of the filename as an argument, although that would be a really rare case.

**Comment by noctuid** [comment]
Yeah it looks like a lot of these commands will need escaping. I think I may be able to remove the surrounding single quotes for some commands. It would be nice if there was version of os.execute that accepted an array instead (not sure if there is). I will look into it.
